global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:8888']
      - targets: ['0.0.0.0:8889']
      - targets: ['0.0.0.0:8890']
      - targets: ['0.0.0.0:8891']
      - targets: ['0.0.0.0:10500']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['0.0.0.0:9100']
